//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndividueelProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class BestellingProduct
    {
        public int Id { get; set; }
        public Nullable<int> IdBestelling { get; set; }
        public Nullable<int> IdProduct { get; set; }
        public Nullable<int> Aantal { get; set; }
    }
}
