//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndividueelProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personeelslid
    {
        public int Id { get; set; }
        public string Voornaam { get; set; }
        public string Achternaam { get; set; }
        public string Login { get; set; }
        public string Wachtwoord { get; set; }
        public string Afdeling { get; set; }
    }
}
