//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndividueelProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Naam { get; set; }
        public Nullable<decimal> Inkoopprijs { get; set; }
        public Nullable<decimal> Marge { get; set; }
        public string Eenheid { get; set; }
        public Nullable<decimal> BTW { get; set; }
        public Nullable<int> IdLeverancier { get; set; }
        public Nullable<int> IdSubcategorie { get; set; }
    }
}
